### ISSUE TITLE
Make coffee dependency optional

### ISSUE THREAD

**Issue by StreetStrider** [mjpizz/better-stack-traces#4]
Hello. For those who do not need CoffeeScript it would be better not to have it as dependency of `better-stack-traces` at all.

I've looked through code and found that there's a place for customization: `this._coffee`
```javascript
this._coffee = opt.coffee || req("coffee-script") || win.CoffeeScript;
```
I would recommend to get rid of 2nd part `req("coffee-script")` and mark CS dependency as optional.

By the way, `require` is a synchronous function and it throws error when it can't find a module. So this line won't work as you expected.

The proper implementation may be such:
```javascript
function req (mod) {
  try {
    return require(mod);
  } catch (e) {
    return null;
  }
}
```

I'm hoping this module is still maintained.
Best regards. Waiting for answer.

**Comment by mjpizz** [comment]
Thanks StreetStrider, moved this over into a pull request https://github.com/mjpizz/better-stack-traces/pull/5
